// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: api/obd.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleOBD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Pid           string                 `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Param         string                 `protobuf:"bytes,4,opt,name=param,proto3" json:"param,omitempty"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleOBD) Reset() {
	*x = VehicleOBD{}
	mi := &file_api_obd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleOBD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleOBD) ProtoMessage() {}

func (x *VehicleOBD) ProtoReflect() protoreflect.Message {
	mi := &file_api_obd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleOBD.ProtoReflect.Descriptor instead.
func (*VehicleOBD) Descriptor() ([]byte, []int) {
	return file_api_obd_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleOBD) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleOBD) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *VehicleOBD) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *VehicleOBD) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *VehicleOBD) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *VehicleOBD) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_api_obd_proto protoreflect.FileDescriptor

const file_api_obd_proto_rawDesc = "" +
	"\n" +
	"\rapi/obd.proto\x12\x03obd\"\x8a\x01\n" +
	"\n" +
	"VehicleOBD\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\tR\x03pid\x12\x14\n" +
	"\x05param\x18\x04 \x01(\tR\x05param\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unitB9Z7github.com/jojohimawan/intelligent-agent-system/api;apib\x06proto3"

var (
	file_api_obd_proto_rawDescOnce sync.Once
	file_api_obd_proto_rawDescData []byte
)

func file_api_obd_proto_rawDescGZIP() []byte {
	file_api_obd_proto_rawDescOnce.Do(func() {
		file_api_obd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_obd_proto_rawDesc), len(file_api_obd_proto_rawDesc)))
	})
	return file_api_obd_proto_rawDescData
}

var file_api_obd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_obd_proto_goTypes = []any{
	(*VehicleOBD)(nil), // 0: obd.VehicleOBD
}
var file_api_obd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_obd_proto_init() }
func file_api_obd_proto_init() {
	if File_api_obd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_obd_proto_rawDesc), len(file_api_obd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_obd_proto_goTypes,
		DependencyIndexes: file_api_obd_proto_depIdxs,
		MessageInfos:      file_api_obd_proto_msgTypes,
	}.Build()
	File_api_obd_proto = out.File
	file_api_obd_proto_goTypes = nil
	file_api_obd_proto_depIdxs = nil
}
